name: REACT CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: tylegg
        
      - name: Setup .env
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> tylegg/.env
          echo "REACT_APP_CUR_URL=${{ secrets.REACT_APP_CUR_URL }}" >> tylegg/.env

          
          

      - name: Build
        run: npm run build
        working-directory: tylegg

      - name: Upload to S3 Bucket
        uses: awact/s3-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'tylegg/build'
          AWS_REGION: 'ap-northeast-2'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_DEV_WEB_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_PRIVATE_KEY }}
